name: rosemary_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  easy_date_timeline: ^1.1.3
  google_nav_bar: ^5.0.6
  calendar_date_picker2: ^1.1.7
  omni_datetime_picker: ^2.0.5
  intl: ^0.19.0
  pomodoro4d: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
